# Generated by Django 5.1.3 on 2025-12-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_conteact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conteact',
            new_name='Contact',
        ),
    ]
