# Generated by Django 5.1.3 on 2025-12-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_conteact_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
