# Generated by Django 5.1.3 on 2025-12-05 08:49

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_document'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contact',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'jpg', 'png'])], verbose_name='document'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user', 'email', 'image', 'document')},
        ),
    ]
